### PR TITLE
Remove the criteria for acceptance testing from Dragon

### PR DESCRIPTION
**Pull request by adrianclay**
While Richard and I are keen to have the concept of acceptance testing
included within the testing core skill we can't currently see a way to
include it within the 3 badges.

We can reconsider this at a later date, possibly by introducing the
concept of a new badge.

### CODE REVIEW

**Comment by craigjbass** [comment]
Why can’t it be included at Dragon?

**Comment by craigjbass** [comment]
What would the badge above dragon look like?

**Comment by craigjbass** [comment]
Getting stale

**Comment by zuren** [comment]
Need to begin testing of Dragon, so will merge. Will discuss acceptance testing options later.  Seems out of place with the rest of the criteria here.

**Pull request merged**
